server:
  port: 8083
spring:
  application:
    name: user-service
  datasource:
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    validation-query: select 1
    test-on-borrow: true
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false
    jpa:
      database-platform: ${SPRING_JPA_DATABASE-PLATFORM}
  liquibase:
    enabled: true
    defaultSchema: users
    liquibaseSchema: users
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761}/eureka/
    eureka-server-port: 8761
    register-with-eureka: true
    fetch-registry: true
