server:
    port: 8083
spring:
    datasource:
        password: start123
        url: jdbc:postgresql://3.18.104.249:5432/postgres?currentSchema=users
        username: postgres
    flyway:
        baseline-on-migrate: true
        enabled: true
        schemas: users
    jpa:
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true
                temp:
                    use_jdbc_metadata_defaults: false
