server:
  port: 8083
spring:
  application:
    name: user-service
  datasource:
    password: start123
    url: jdbc:postgresql://3.18.104.249:5432/postgres?currentSchema=users
    username: postgres
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false
  liquibase:
    enabled: true
    defaultSchema: users
    liquibaseSchema: users
